const actionTypes = Object.freeze({
    //app
    APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
    SET_CONTENT_OF_CONFIRM_MODAL: 'SET_CONTENT_OF_CONFIRM_MODAL',
    CHANGE_LANGUAGE: 'CHANGE_LANGUAGE',

    //user
    ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',
    PROCESS_LOGOUT: 'PROCESS_LOGOUT',

    FETCH_GENDER_START: 'FETCH_GENDER_START',
    FETCH_GENDER_SUCCESS: 'FETCH_GENDER_SUCCESS',
    FETCH_GENDER_FAILED: 'FETCH_GENDER_FAILED',

    FETCH_ROLE_START: 'FETCH_ROLE_START',
    FETCH_ROLE_SUCCESS: 'FETCH_ROLE_SUCCESS',
    FETCH_ROLE_FAILED: 'FETCH_ROLE_FAILED',

    CREATE_USER_START: 'CREATE_USER_START',
    CREATE_USER_SUCCESS: 'CREATE_USER_SUCCESS',
    CREATE_USER_FAILED: 'CREATE_USER_FAILED',

    COUNT_STAFF_START: 'COUNT_STAFF_START',
    COUNT_STAFF_SUCCESS: 'COUNT_STAFF_SUCCESS',
    COUNT_STAFF_FAILED: 'COUNT_STAFF_FAILED',

    FETCH_ALL_USERS_START: 'FETCH_ALL_USERS_START',
    FETCH_ALL_USERS_SUCCESS: 'FETCH_ALL_USERS_SUCCESS',
    FETCH_ALL_USERS_FAILED: 'FETCH_ALL_USERS_FAILED',

    FETCH_ALL_STAFFS_WORKING_START: 'FETCH_ALL_STAFFS_WORKING_START',
    FETCH_ALL_STAFFS_WORKING_SUCCESS: 'FETCH_ALL_STAFFS_WORKING_SUCCESS',
    FETCH_ALL_STAFFS_WORKING_FAILED: 'FETCH_ALL_STAFFS_WORKING_FAILED',

    DELETE_USER_START: 'DELETE_USER_START',
    DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',
    DELETE_USER_FAILED: 'DELETE_USER_FAILED',

    EDIT_USER_START: 'EDIT_USER_START',
    EDIT_USER_SUCCESS: 'EDIT_USER_SUCCESS',
    EDIT_USER_FAILED: 'EDIT_USER_FAILED',

    FIND_USER_START: 'FIND_USER_START',
    FIND_USER_SUCCESS: 'FIND_USER_SUCCESS',
    FIND_USER_FAILED: 'FIND_USER_FAILED',

    //Calendar

    CREATE_CALENDAR_START: 'CREATE_CALENDAR_START',
    CREATE_CALENDAR_SUCCESS: 'CREATE_CALENDAR_SUCCESS',
    CREATE_CALENDAR_FAILED: 'CREATE_CALENDAR_FAILED',

    FETCH_ALL_CALENDAR_START: 'FETCH_ALL_CALENDAR_START',
    FETCH_ALL_CALENDAR_SUCCESS: 'FETCH_ALL_CALENDAR_SUCCESS',
    FETCH_ALL_CALENDAR_FAILED: 'FETCH_ALL_CALENDAR_FAILED',

    FETCH_ALL_CALENDAR_DEAD_START: 'FETCH_ALL_CALENDAR_DEAD_START',
    FETCH_ALL_CALENDAR_DEAD_SUCCESS: 'FETCH_ALL_CALENDAR_DEAD_SUCCESS',
    FETCH_ALL_CALENDAR_DEAD_FAILED: 'FETCH_ALL_CALENDAR_DEAD_FAILED',

    FETCH_CALENDAR_DEAD_TODAY_START: 'FETCH_CALENDAR_DEAD_TODAY_START',
    FETCH_CALENDAR_DEAD_TODAY_SUCCESS: 'FETCH_CALENDAR_DEAD_TODAY_SUCCESS',
    FETCH_CALENDAR_DEAD_TODAY_FAILED: 'FETCH_CALENDAR_DEAD_TODAY_FAILED',

    FETCH_ALL_CALENDAR_LATE_START: 'FETCH_ALL_CALENDAR_LATE_START',
    FETCH_ALL_CALENDAR_LATE_SUCCESS: 'FETCH_ALL_CALENDAR_LATE_SUCCESS',
    FETCH_ALL_CALENDAR_LATE_FAILED: 'FETCH_ALL_CALENDAR_LATE_FAILED',

    FETCH_ALL_CALENDAR_FINISHED_START: 'FETCH_ALL_CALENDAR_FINISHED_START',
    FETCH_ALL_CALENDAR_FINISHED_SUCCESS: 'FETCH_ALL_CALENDAR_FINISHED_SUCCESS',
    FETCH_ALL_CALENDAR_FINISHED_FAILED: 'FETCH_ALL_CALENDAR_FINISHED_FAILED',

    DELETE_CALENDAR_START: 'DELETE_CALENDAR_START',
    DELETE_CALENDAR_SUCCESS: 'DELETE_CALENDAR_SUCCESS',
    DELETE_CALENDAR_FAILED: 'DELETE_CALENDAR_FAILED',

    EDIT_CALENDAR_START: 'EDIT_CALENDAR_START',
    EDIT_CALENDAR_SUCCESS: 'EDIT_CALENDAR_SUCCESS',
    EDIT_CALENDAR_FAILED: 'EDIT_CALENDAR_FAILED',

})

export default actionTypes;