const actionTypes = Object.freeze({
    //app
    APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
    SET_CONTENT_OF_CONFIRM_MODAL: 'SET_CONTENT_OF_CONFIRM_MODAL',
    CHANGE_LANGUAGE: 'CHANGE_LANGUAGE',

    //user
    ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',
    PROCESS_LOGOUT: 'PROCESS_LOGOUT',

    FETCH_GENDER_START: 'FETCH_GENDER_START',
    FETCH_GENDER_SUCCESS: 'FETCH_GENDER_SUCCESS',
    FETCH_GENDER_FAILED: 'FETCH_GENDER_FAILED',

    FETCH_ROLE_START: 'FETCH_ROLE_START',
    FETCH_ROLE_SUCCESS: 'FETCH_ROLE_SUCCESS',
    FETCH_ROLE_FAILED: 'FETCH_ROLE_FAILED',

    CREATE_USER_START: 'CREATE_USER_START',
    CREATE_USER_SUCCESS: 'CREATE_USER_SUCCESS',
    CREATE_USER_FAILED: 'CREATE_USER_FAILED',

    COUNT_STAFF_START: 'COUNT_STAFF_START',
    COUNT_STAFF_SUCCESS: 'COUNT_STAFF_SUCCESS',
    COUNT_STAFF_FAILED: 'COUNT_STAFF_FAILED',

    FETCH_ALL_USERS_START: 'FETCH_ALL_USERS_START',
    FETCH_ALL_USERS_SUCCESS: 'FETCH_ALL_USERS_SUCCESS',
    FETCH_ALL_USERS_FAILED: 'FETCH_ALL_USERS_FAILED',

    FETCH_ALL_STAFFS_WORKING_START: 'FETCH_ALL_STAFFS_WORKING_START',
    FETCH_ALL_STAFFS_WORKING_SUCCESS: 'FETCH_ALL_STAFFS_WORKING_SUCCESS',
    FETCH_ALL_STAFFS_WORKING_FAILED: 'FETCH_ALL_STAFFS_WORKING_FAILED',

    DELETE_USER_START: 'DELETE_USER_START',
    DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',
    DELETE_USER_FAILED: 'DELETE_USER_FAILED',

    EDIT_USER_START: 'EDIT_USER_START',
    EDIT_USER_SUCCESS: 'EDIT_USER_SUCCESS',
    EDIT_USER_FAILED: 'EDIT_USER_FAILED',

    FIND_USER_START: 'FIND_USER_START',
    FIND_USER_SUCCESS: 'FIND_USER_SUCCESS',
    FIND_USER_FAILED: 'FIND_USER_FAILED',

    //Product
    DETAIL_UPDATE_PRODUCT_START: 'DETAIL_UPDATE_PRODUCT_START',
    DETAIL_UPDATE_PRODUCT_SUCCESS: 'DETAIL_UPDATE_PRODUCT_SUCCESS',
    DETAIL_UPDATE_PRODUCT_FAILED: 'DETAIL_UPDATE_PRODUCT_FAILED',

    CREATE_PRODUCT_START: 'CREATE_PRODUCT_START',
    CREATE_PRODUCT_SUCCESS: 'CREATE_PRODUCT_SUCCESS',
    CREATE_PRODUCT_FAILED: 'CREATE_PRODUCT_FAILED',

    CREATE_PRODUCT_EXPORT_START: 'CREATE_PRODUCT_EXPORT_START',
    CREATE_PRODUCT_EXPORT_SUCCESS: 'CREATE_PRODUCT_EXPORT_SUCCESS',
    CREATE_PRODUCT_EXPORT_FAILED: 'CREATE_PRODUCT_EXPORT_FAILED',

    CREATE_PRODUCT_UPDATE_START: 'CREATE_PRODUCT_UPDATE_START',
    CREATE_PRODUCT_UPDATE_SUCCESS: 'CREATE_PRODUCT_UPDATE_SUCCESS',
    CREATE_PRODUCT_UPDATE_FAILED: 'CREATE_PRODUCT_UPDATE_FAILED',

    FETCH_ALL_PRODUCTS_START: 'FETCH_ALL_PRODUCTS_START',
    FETCH_ALL_PRODUCTS_SUCCESS: 'FETCH_ALL_PRODUCTS_SUCCESS',
    FETCH_ALL_PRODUCTS_FAILED: 'FETCH_ALL_PRODUCTS_FAILED',

    DELETE_PRODUCT_START: 'DELETE_PRODUCT_START',
    DELETE_PRODUCT_SUCCESS: 'DELETE_PRODUCT_SUCCESS',
    DELETE_PRODUCT_FAILED: 'DELETE_PRODUCT_FAILED',

    DELETE_IMPORT_PRODUCT_START: 'DELETE_IMPORT_PRODUCT_START',
    DELETE_IMPORT_PRODUCT_SUCCESS: 'DELETE_IMPORT_PRODUCT_SUCCESS',
    DELETE_IMPORT_PRODUCT_FAILED: 'DELETE_IMPORT_PRODUCT_FAILED',

    EDIT_PRODUCT_START: 'EDIT_PRODUCT_START',
    EDIT_PRODUCT_SUCCESS: 'EDIT_PRODUCT_SUCCESS',
    EDIT_PRODUCT_FAILED: 'EDIT_PRODUCT_FAILED',

    FETCH_BUY_PRO_START: 'FETCH_BUY_PRO_START',
    FETCH_BUY_PRO_SUCCESS: 'FETCH_BUY_PRO_SUCCESS',
    FETCH_BUY_PRO_FAILED: 'FETCH_BUY_PRO_FAILED',

    //Unit
    FETCH_UNIT_START: 'FETCH_UNIT_START',
    FETCH_UNIT_SUCCESS: 'FETCH_UNIT_SUCCESS',
    FETCH_UNIT_FAILED: 'FETCH_UNIT_FAILED',

    CREATE_UNIT_START: 'CREATE_UNIT_START',
    CREATE_UNIT_SUCCESS: 'CREATE_UNIT_SUCCESS',
    CREATE_UNIT_FAILED: 'CREATE_UNIT_FAILED',

    EDIT_UNIT_START: 'EDIT_UNIT_START',
    EDIT_UNIT_SUCCESS: 'EDIT_UNIT_SUCCESS',
    EDIT_UNIT_FAILED: 'EDIT_UNIT_FAILED',

    DELETE_UNIT_START: 'DELETE_UNIT_START',
    DELETE_UNIT_SUCCESS: 'DELETE_UNIT_SUCCESS',
    DELETE_UNIT_FAILED: 'DELETE_UNIT_FAILED',

    //Service
    FETCH_SERVICE_THEME_START: 'FETCH_SERVICE_THEME_START',
    FETCH_SERVICE_THEME_SUCCESS: 'FETCH_SERVICE_THEME_SUCCESS',
    FETCH_SERVICE_THEME_FAILED: 'FETCH_SERVICE_THEME_FAILED',

    SERVICE_WITH_TYPE_START: 'SERVICE_WITH_TYPE_START',
    SERVICE_WITH_TYPE_SUCCESS: 'SERVICE_WITH_TYPE_SUCCESS',
    SERVICE_WITH_TYPE_FAILED: 'SERVICE_WITH_TYPE_FAILED',

    CREATE_SERVICE_START: 'CREATE_SERVICE_START',
    CREATE_SERVICE_SUCCESS: 'CREATE_SERVICE_SUCCESS',
    CREATE_SERVICE_FAILED: 'CREATE_SERVICE_FAILED',

    CREATE_SERVICE_TYPE_START: 'CREATE_SERVICE_TYPE_START',
    CREATE_SERVICE_TYPE_SUCCESS: 'CREATE_SERVICE_TYPE_SUCCESS',
    CREATE_SERVICE_TYPE_FAILED: 'CREATE_SERVICE_TYPE_FAILED',

    FETCH_ALL_SERVICES_START: 'FETCH_ALL_SERVICES_START',
    FETCH_ALL_SERVICES_SUCCESS: 'FETCH_ALL_SERVICES_SUCCESS',
    FETCH_ALL_SERVICES_FAILED: 'FETCH_ALL_SERVICES_FAILED',

    FETCH_SERVICES_TYPE_START: 'FETCH_SERVICES_TYPE_START',
    FETCH_SERVICES_TYPE_SUCCESS: 'FETCH_SERVICES_TYPE_SUCCESS',
    FETCH_SERVICES_TYPE_FAILED: 'FETCH_SERVICES_TYPE_FAILED',

    DELETE_SERVICE_START: 'DELETE_SERVICE_START',
    DELETE_SERVICE_SUCCESS: 'DELETE_SERVICE_SUCCESS',
    DELETE_SERVICE_FAILED: 'DELETE_SERVICE_FAILED',

    DELETE_SERVICE_TYPE_START: 'DELETE_SERVICE_TYPE_START',
    DELETE_SERVICE_TYPE_SUCCESS: 'DELETE_SERVICE_TYPE_SUCCESS',
    DELETE_SERVICE_TYPE_FAILED: 'DELETE_SERVICE_TYPE_FAILED',

    EDIT_SERVICE_START: 'EDIT_SERVICE_START',
    EDIT_SERVICE_SUCCESS: 'EDIT_SERVICE_SUCCESS',
    EDIT_SERVICE_FAILED: 'EDIT_SERVICE_FAILED',

    EDIT_SERVICE_TYPE_START: 'EDIT_SERVICE_TYPE_START',
    EDIT_SERVICE_TYPE_SUCCESS: 'EDIT_SERVICE_TYPE_SUCCESS',
    EDIT_SERVICE_TYPE_FAILED: 'EDIT_SERVICE_TYPE_FAILED',

    //Schedule
    FETCH_TIME_TYPE_START: 'FETCH_TIME_TYPE_START',
    FETCH_TIME_TYPE_SUCCESS: 'FETCH_TIME_TYPE_SUCCESS',
    FETCH_TIME_TYPE_FAILED: 'FETCH_TIME_TYPE_FAILED',

    CREATE_SCHEDULE_START: 'CREATE_SCHEDULE_START',
    CREATE_SCHEDULE_SUCCESS: 'CREATE_SCHEDULE_SUCCESS',
    CREATE_SCHEDULE_FAILED: 'CREATE_SCHEDULE_FAILED',

    FETCH_ALL_SCHEDULES_START: 'FETCH_ALL_SCHEDULES_START',
    FETCH_ALL_SCHEDULES_SUCCESS: 'FETCH_ALL_SCHEDULES_SUCCESS',
    FETCH_ALL_SCHEDULES_FAILED: 'FETCH_ALL_SCHEDULES_FAILED',

    DELETE_SCHEDULE_START: 'DELETE_SCHEDULE_START',
    DELETE_SCHEDULE_SUCCESS: 'DELETE_SCHEDULE_SUCCESS',
    DELETE_SCHEDULE_FAILED: 'DELETE_SCHEDULE_FAILED',

    EDIT_SCHEDULE_START: 'EDIT_SCHEDULE_START',
    EDIT_SCHEDULE_SUCCESS: 'EDIT_SCHEDULE_SUCCESS',
    EDIT_SCHEDULE_FAILED: 'EDIT_SCHEDULE_FAILED',

    //Calendar

    CREATE_CALENDAR_START: 'CREATE_CALENDAR_START',
    CREATE_CALENDAR_SUCCESS: 'CREATE_CALENDAR_SUCCESS',
    CREATE_CALENDAR_FAILED: 'CREATE_CALENDAR_FAILED',

    FETCH_ALL_CALENDAR_START: 'FETCH_ALL_CALENDAR_START',
    FETCH_ALL_CALENDAR_SUCCESS: 'FETCH_ALL_CALENDAR_SUCCESS',
    FETCH_ALL_CALENDAR_FAILED: 'FETCH_ALL_CALENDAR_FAILED',

    FETCH_ALL_CALENDAR_DEAD_START: 'FETCH_ALL_CALENDAR_DEAD_START',
    FETCH_ALL_CALENDAR_DEAD_SUCCESS: 'FETCH_ALL_CALENDAR_DEAD_SUCCESS',
    FETCH_ALL_CALENDAR_DEAD_FAILED: 'FETCH_ALL_CALENDAR_DEAD_FAILED',

    DELETE_CALENDAR_START: 'DELETE_CALENDAR_START',
    DELETE_CALENDAR_SUCCESS: 'DELETE_CALENDAR_SUCCESS',
    DELETE_CALENDAR_FAILED: 'DELETE_CALENDAR_FAILED',

    EDIT_CALENDAR_START: 'EDIT_CALENDAR_START',
    EDIT_CALENDAR_SUCCESS: 'EDIT_CALENDAR_SUCCESS',
    EDIT_CALENDAR_FAILED: 'EDIT_CALENDAR_FAILED',

    //Booking
    CREATE_BOOKING_START: 'CREATE_BOOKING_START',
    CREATE_BOOKING_SUCCESS: 'CREATE_BOOKING_SUCCESS',
    CREATE_BOOKING_FAILED: 'CREATE_BOOKING_FAILED',

    CREATE_CALL_BOOKING_START: 'CREATE_CALL_BOOKING_START',
    CREATE_CALL_BOOKING_SUCCESS: 'CREATE_CALL_BOOKING_SUCCESS',
    CREATE_CALL_BOOKING_FAILED: 'CREATE_CALL_BOOKING_FAILED',

    EDIT_BOOKING_START: 'EDIT_BOOKING_START',
    EDIT_BOOKING_SUCCESS: 'EDIT_BOOKING_SUCCESS',
    EDIT_BOOKING_FAILED: 'EDIT_BOOKING_FAILED',

    GET_CALL_BOOKING_OFDATE_START: 'GET_CALL_BOOKING_OFDATE_START',
    GET_CALL_BOOKING_OFDATE_SUCCESS: 'GET_CALL_BOOKING_OFDATE_SUCCESS',
    GET_CALL_BOOKING_OFDATE_FAILED: 'GET_CALL_BOOKING_OFDATE_FAILED',

    FETCH_ALL_BOOKINGS_START: 'FETCH_ALL_BOOKINGS_START',
    FETCH_ALL_BOOKINGS_SUCCESS: 'FETCH_ALL_BOOKINGS_SUCCESS',
    FETCH_ALL_BOOKINGS_FAILED: 'FETCH_ALL_BOOKINGS_FAILED',

    GET_BOOKING_SALARY_START: 'GET_BOOKING_SALARY_START',
    GET_BOOKING_SALARY_SUCCESS: 'GET_BOOKING_SALARY_SUCCESS',
    GET_BOOKING_SALARY_FAILED: 'GET_BOOKING_SALARY_FAILED',

    DELETE_BOOKING_START: 'DELETE_BOOKING_START',
    DELETE_BOOKING_SUCCESS: 'DELETE_BOOKING_SUCCESS',
    DELETE_BOOKING_FAILED: 'DELETE_BOOKING_FAILED',

    DELETE_CALL_BOOKING_START: 'DELETE_CALL_BOOKING_START',
    DELETE_CALL_BOOKING_SUCCESS: 'DELETE_CALL_BOOKING_SUCCESS',
    DELETE_CALL_BOOKING_FAILED: 'DELETE_CALL_BOOKING_FAILED',

    EDIT_CALL_BOOKING_START: 'EDIT_CALL_BOOKING_START',
    EDIT_CALL_BOOKING_SUCCESS: 'EDIT_CALL_BOOKING_SUCCESS',
    EDIT_CALL_BOOKING_FAILED: 'EDIT_CALL_BOOKING_FAILED',

    //Tax
    CREATE_TAX_START: 'CREATE_TAX_START',
    CREATE_TAX_SUCCESS: 'CREATE_TAX_SUCCESS',
    CREATE_TAX_FAILED: 'CREATE_TAX_FAILED',

    FETCH_ALL_TAXS_START: 'FETCH_ALL_TAXS_START',
    FETCH_ALL_TAXS_SUCCESS: 'FETCH_ALL_TAXS_SUCCESS',
    FETCH_ALL_TAXS_FAILED: 'FETCH_ALL_TAXS_FAILED',

    GET_TAX_NOW_START: 'GET_TAX_NOW_START',
    GET_TAX_NOW_SUCCESS: 'GET_TAX_NOW_SUCCESS',
    GET_TAX_NOW_FAILED: 'GET_TAX_NOW_FAILED',

    EDIT_TAX_START: 'EDIT_TAX_START',
    EDIT_TAX_SUCCESS: 'EDIT_TAX_SUCCESS',
    EDIT_TAX_FAILED: 'EDIT_TAX_FAILED',

    //Salary
    CREATE_SALARY_START: 'CREATE_SALARY_START',
    CREATE_SALARY_SUCCESS: 'CREATE_SALARY_SUCCESS',
    CREATE_SALARY_FAILED: 'CREATE_SALARY_FAILED',

    FETCH_ALL_SALARY_START: 'FETCH_ALL_SALARY_START',
    FETCH_ALL_SALARY_SUCCESS: 'FETCH_ALL_SALARY_SUCCESS',
    FETCH_ALL_SALARY_FAILED: 'FETCH_ALL_SALARY_FAILED',

    DELETE_SALARY_START: 'DELETE_SALARY_START',
    DELETE_SALARY_SUCCESS: 'DELETE_SALARY_SUCCESS',
    DELETE_SALARY_FAILED: 'DELETE_SALARY_FAILED',

    EDIT_SALARY_START: 'EDIT_SALARY_START',
    EDIT_SALARY_SUCCESS: 'EDIT_SALARY_SUCCESS',
    EDIT_SALARY_FAILED: 'EDIT_SALARY_FAILED',

})

export default actionTypes;